// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: mao-server-discovery.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServerReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok          bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Hostname    string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ips         []string `protobuf:"bytes,3,rep,name=ips,proto3" json:"ips,omitempty"`
	NowDatetime string   `protobuf:"bytes,4,opt,name=now_datetime,json=nowDatetime,proto3" json:"now_datetime,omitempty"`
	AuxData     string   `protobuf:"bytes,5,opt,name=aux_data,json=auxData,proto3" json:"aux_data,omitempty"` // other Incubator or Aux data
}

func (x *ServerReport) Reset() {
	*x = ServerReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_server_discovery_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerReport) ProtoMessage() {}

func (x *ServerReport) ProtoReflect() protoreflect.Message {
	mi := &file_mao_server_discovery_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerReport.ProtoReflect.Descriptor instead.
func (*ServerReport) Descriptor() ([]byte, []int) {
	return file_mao_server_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *ServerReport) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ServerReport) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerReport) GetIps() []string {
	if x != nil {
		return x.Ips
	}
	return nil
}

func (x *ServerReport) GetNowDatetime() string {
	if x != nil {
		return x.NowDatetime
	}
	return ""
}

func (x *ServerReport) GetAuxData() string {
	if x != nil {
		return x.AuxData
	}
	return ""
}

type ServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname   string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	NewAddress string `protobuf:"bytes,2,opt,name=new_address,json=newAddress,proto3" json:"new_address,omitempty"`
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_server_discovery_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mao_server_discovery_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_mao_server_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *ServerResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ServerResponse) GetNewAddress() string {
	if x != nil {
		return x.NewAddress
	}
	return ""
}

type RttEchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
}

func (x *RttEchoRequest) Reset() {
	*x = RttEchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_server_discovery_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RttEchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttEchoRequest) ProtoMessage() {}

func (x *RttEchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mao_server_discovery_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttEchoRequest.ProtoReflect.Descriptor instead.
func (*RttEchoRequest) Descriptor() ([]byte, []int) {
	return file_mao_server_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *RttEchoRequest) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type RttEchoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Ack      uint64 `protobuf:"varint,2,opt,name=ack,proto3" json:"ack,omitempty"`
}

func (x *RttEchoResponse) Reset() {
	*x = RttEchoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mao_server_discovery_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RttEchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RttEchoResponse) ProtoMessage() {}

func (x *RttEchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mao_server_discovery_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RttEchoResponse.ProtoReflect.Descriptor instead.
func (*RttEchoResponse) Descriptor() ([]byte, []int) {
	return file_mao_server_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *RttEchoResponse) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RttEchoResponse) GetAck() uint64 {
	if x != nil {
		return x.Ack
	}
	return 0
}

var File_mao_server_discovery_proto protoreflect.FileDescriptor

var file_mao_server_discovery_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x61, 0x6f, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x4d, 0x61,
	0x6f, 0x22, 0x8a, 0x01, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02,
	0x6f, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x69, 0x70, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x70, 0x73,
	0x12, 0x21, 0x0a, 0x0c, 0x6e, 0x6f, 0x77, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6e, 0x6f, 0x77, 0x44, 0x61, 0x74, 0x65, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x75, 0x78, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x75, 0x78, 0x44, 0x61, 0x74, 0x61, 0x22, 0x4d,
	0x0a, 0x0e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b,
	0x6e, 0x65, 0x77, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x6e, 0x65, 0x77, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x22, 0x0a,
	0x0e, 0x52, 0x74, 0x74, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x73, 0x65,
	0x71, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x74, 0x74, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x61,
	0x63, 0x6b, 0x32, 0x8b, 0x01, 0x0a, 0x12, 0x4d, 0x61, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x36, 0x0a, 0x06, 0x52, 0x65, 0x70,
	0x6f, 0x72, 0x74, 0x12, 0x11, 0x2e, 0x4d, 0x61, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x1a, 0x13, 0x2e, 0x4d, 0x61, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x12, 0x3d, 0x0a, 0x0a, 0x52, 0x74, 0x74, 0x4d, 0x65, 0x61, 0x73, 0x75, 0x72, 0x65, 0x12,
	0x14, 0x2e, 0x4d, 0x61, 0x6f, 0x2e, 0x52, 0x74, 0x74, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x1a, 0x13, 0x2e, 0x4d, 0x61, 0x6f, 0x2e, 0x52, 0x74, 0x74, 0x45,
	0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01,
	0x42, 0x2a, 0x5a, 0x28, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x6d, 0x61, 0x6f, 0x6a, 0x69, 0x61, 0x6e,
	0x77, 0x65, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mao_server_discovery_proto_rawDescOnce sync.Once
	file_mao_server_discovery_proto_rawDescData = file_mao_server_discovery_proto_rawDesc
)

func file_mao_server_discovery_proto_rawDescGZIP() []byte {
	file_mao_server_discovery_proto_rawDescOnce.Do(func() {
		file_mao_server_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(file_mao_server_discovery_proto_rawDescData)
	})
	return file_mao_server_discovery_proto_rawDescData
}

var file_mao_server_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mao_server_discovery_proto_goTypes = []interface{}{
	(*ServerReport)(nil),    // 0: Mao.ServerReport
	(*ServerResponse)(nil),  // 1: Mao.ServerResponse
	(*RttEchoRequest)(nil),  // 2: Mao.RttEchoRequest
	(*RttEchoResponse)(nil), // 3: Mao.RttEchoResponse
}
var file_mao_server_discovery_proto_depIdxs = []int32{
	0, // 0: Mao.MaoServerDiscovery.Report:input_type -> Mao.ServerReport
	3, // 1: Mao.MaoServerDiscovery.RttMeasure:input_type -> Mao.RttEchoResponse
	1, // 2: Mao.MaoServerDiscovery.Report:output_type -> Mao.ServerResponse
	2, // 3: Mao.MaoServerDiscovery.RttMeasure:output_type -> Mao.RttEchoRequest
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mao_server_discovery_proto_init() }
func file_mao_server_discovery_proto_init() {
	if File_mao_server_discovery_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mao_server_discovery_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_server_discovery_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_server_discovery_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RttEchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mao_server_discovery_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RttEchoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mao_server_discovery_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mao_server_discovery_proto_goTypes,
		DependencyIndexes: file_mao_server_discovery_proto_depIdxs,
		MessageInfos:      file_mao_server_discovery_proto_msgTypes,
	}.Build()
	File_mao_server_discovery_proto = out.File
	file_mao_server_discovery_proto_rawDesc = nil
	file_mao_server_discovery_proto_goTypes = nil
	file_mao_server_discovery_proto_depIdxs = nil
}
